/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qtsczhmwikzsqoklltub"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0c2N6aG13aWt6c3Fva2xsdHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3MzQ2NDgsImV4cCI6MjA3OTMxMDY0OH0.oZvLYro9W-pLEQFuVa_ggLyDoK7awc7t-6ZlEq1zKig"